#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y install haproxy
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo chown "$USER":"$USER" /etc/default/haproxy

echo "ENABLED=1" >> /etc/default/haproxy

sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 158828-web-01 34.204.61.53:80 check\n\tserver 158828-web-02 54.197.45.155:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy start
